language: python
python:
  - "3.7"
install:
  - cd backend/
  - pip install -r requirements.txt
  - pip install codecov==2.0.15
script:
  - pwd
  - ls
  - cd tests/
  - pwd
  - ls 
  - pytest --cov=../ testTask.py
  - pytest testTimer.py
  - pytest testTaskLists.py
  - pytest testUtilities.py
  - pytest testTasksToTimers.py
  - pytest testTimerToUser.py
  - pytest testBoundaryTaskLists.py
  - pytest testBoundaryTasks.py
  - pytest testBoundaryTasksToTimers.py
  - pytest TestBoundaryTimer.py
  - pytest testBoundaryTimerToUser.py

