language: python
python:
  - "3.7"
install:
  - cd backend/
  - pip install -r requirements.txt
env:
  - MYSQL_PASSWORD = 'admin123'
script:
  - pwd
  - ls
  - cd tests/
  - pwd
  - ls 
  - pytest testTask.py
  
